---
name: Prevent manual changes of initial-data.json without md5 hash
on:
  pull_request:
    paths:
      - "docker/initial-data.json"
env:
  PYTHON_VERSION: 3.9.6
jobs:
  validate-data:
    name: Validate example-data.json and initial-data.json
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Show hash for initial-data.json
        run: md5sum docker/initial-data.json

      - name: Validate and protect initial-data.json
        run: echo "624968a911ee12de8b97f4049b493146 docker/initial-data.json" | md5sum -c -
