---
name: Prevent manual changes of initial-data.json without md5 hash
on:
  pull_request:
    paths:
      - "docker/initial-data.json"
env:
  PYTHON_VERSION: 3.9.6
jobs:
  validate-data:
    name: Validate example-data.json and initial-data.json
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Show hash for initial-data.json
        run: md5sum docker/initial-data.json

      - name: Validate and protect initial-data.json
        run: echo "d76c51c2044bbdb7a0c4691d0eaeb202 docker/initial-data.json" | md5sum -c -
