name: Validate models.yml and initial and example data
on: [push, pull_request]
env:
  PYTHON_VERSION: 3.9.6
jobs:
  job1:
    name: Name Job 1
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: cat this file
      run: cat .github/workflow/test.yml

  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: show readme.md
      run: cat readme.md

    - name: Protect
      run: echo "79e29bd433253fac11899059d59cebe3 readme.md" | md5sum -c -
